### ISSUE TITLE
feature request: please add compatibility with Navit

### ISSUE THREAD

**Issue by Supermagnum** [markqvist/OpenModem#1]
Navit is a free and open-source, modular, touch screen friendly, car navigation system with GPS tracking, realtime routing engine and support for various vector map formats. It features both a 2D and 3D view of map data.

Navit supports a variety of operating systems and hardware platforms.
It is currently not compatible with APRS.

Navits official web page:
https://www.navit-project.org/

Github page:
https://github.com/navit-gps

Navit Documentation:
http://doxygen.navit-project.org/

Link to the suggestion( patch request):
navit-gps/navit#982

**Comment by markqvist** [comment]
I think this makes a lot of sense. I will commit to adding support for Navit to OpenModem. Since the OpenModem hardware also has a slot for a GPS module, and I already wrote the basic GPS driver and NMEA parsing into the OpenModem firmware, it'd be natural if OpenModem could function as both a GPS source for Navit and a APRS modem.

**Comment by Supermagnum** [comment]
> I think this makes a lot of sense. I will commit to adding support for Navit to OpenModem. Since the OpenModem hardware also has a slot for a GPS module, and I already wrote the basic GPS driver and NMEA parsing into the OpenModem firmware, it'd be natural if OpenModem could function as both a GPS source for Navit and a APRS modem.

That would be great!
The folks at Navit still have to code the support for APRS symbols,I have no clue when that happens.
