### ISSUE TITLE
Firmware from source code not decode packets.

### ISSUE THREAD

**Issue by demonwork** [markqvist/OpenModem#2]
The operation of the firmware obtained from the source code differs from the precompiled firmware. It does not decode packets.
When I connect with the configuration program to the precompiled firmware, in the Audio section I see what is shown in the OpenModem_AFSK1200_v1.05.hex.png screenshot.
![OpenModem_AFSK1200_v1 05 hex](https://user-images.githubusercontent.com/15307649/104284873-92586a80-54d4-11eb-926a-9b1217c66951.png)
When I connect the configuration program to the firmware from the source code, in the Audio section I see what is shown in the OpenModem.hex-from-source.png screenshot.
![OpenModem hex-from-source](https://user-images.githubusercontent.com/15307649/104284941-ac924880-54d4-11eb-8f11-cb5f25ed0c3e.png)

Perhaps this is somehow related.
I assembled the modem according to your scheme, but my cardholder is different. When there is no SD card in it, SD_DETECT is high, when the card is inserted, low. So I had to invert the card presence check and compile the firmware from the source code.

Everything works fine with precompiled firmware. Except for working with a SD card.

My build system is Ubuntu 18.04, avr-libc 2.0.0, gcc-avr 5.4.0.

**Comment by demonwork** [comment]
Fixed the issue and some enhancement in pull request #3

**Comment by markqvist** [comment]
Thanks for reporting it. I normally leave the master branch in a working order, but due to some new drivers, the head of the master branch was not decoding packets. Please always use the sources from the latest tagged release if something is wonky, in rare cases I might be in the middle of something in the head of the master branch ;) Either way, version 1.06 is released now and the issue is resolved. I'll have a look at the pull request later. Thanks for contributing.
