### ISSUE TITLE
Plans to open source board layout files?

### ISSUE THREAD

**Issue by spaceinvadr** [markqvist/OpenModem#6]
Hey Mark, I want to start by saying I've been following your work on Reticulum and RNode for several years and am hugely appreciative of everything you have made available to the community. These projects have been hugely inspirational in my own personal projects and I'm looking forward to watching them continue to develop and enable more people to connect without reliance on internet systems. 

I'm wondering if you have any plans to open-source the board files to enable people to assemble their own openmodem hardware. I realize this is a product you sell and even releasing the schematic files is generous. If you would rather not that is totally understandable.

**Comment by markqvist** [comment]
Thank you very much for your encouraging comments!

That is something I am considering doing, but currently I'm not sure it would add much value, since it is really hard to source several of the parts needed to build the modem, especially the ATmega1284p MCU. I've been working on a redesign to use another chip, but with everything else going on, and priorities putting other work higher, it is not something that is near ready yet.

**Comment by ahedproductions** [comment]
Hello!
This CPU is very much available now!
https://www.mouser.bg/ProductDetail/Microchip-Technology/ATMEGA1284P-AU?qs=K8BHR703ZXhSH38LfIFExQ%3D%3D
I would like to up the question.
Thank you!
